<?php
declare(strict_types=1);
/**
 * @by SwiftOtter, Inc., 2018/06/16
 * @website https://swiftotter.com
 **/
?>
<div class="element-selector"></div>

<script type="text/x-magento-init">
{
  "*": {
    "SwiftOtter_Test/js/test": {
      "details": "test"
    }
  }
}
</script>
<script>
require([
  'jquery',
  'SwiftOtter_Test/js/custom-tabs'], function ($) {
    $(".element-selector").customTabs();
    $(".element-selector").customTabs("doSomething", "hello");
});
</script>
